"""Initial migration

Revision ID: 103e23c89c3c
Revises: 
Create Date: 2025-04-10 20:06:15.228201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103e23c89c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
